spring:
  datasource:
    url: jdbc:h2:mem:delivery;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:test-liquibase-changelog.xml
    liquibase-schema: public
    enabled: true