server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  error:
    include-message: always
spring:
  application:
    name: customer-ms
  main:
    banner-mode: log
  datasource:
    url: jdbc:postgresql://localhost:54321/customer
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      login-timeout: 5000
      connection-test-query: "select 1"
      connection-timeout: 5000
      pool-name: account-service
      idle-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 0
      minimum-idle: 1
      register-mbeans: true
  liquibase:
    change-log: classpath:test-liquibase-changelog.xml
    liquibase-schema: public
    enabled: true

logging:
  level:
    root: INFO