server:
  port: 8084
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  error:
    include-message: always
spring:
  application:
    name: payment-ms
  main:
    banner-mode: log
  datasource:
    url: jdbc:postgresql://localhost:54324/payment
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      login-timeout: 5000
      connection-test-query: "select 1"
      connection-timeout: 5000
      pool-name: account-service
      idle-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 0
      minimum-idle: 1
      register-mbeans: true
  liquibase:
    change-log: classpath:liquibase-changelog.xml
    liquibase-schema: public
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO